### ISSUE TITLE
Bug: Clicking between PCA Visualizations

### ISSUE THREAD

**Issue by TomDonoghue** [PaulScotti/educortex#10]
When I open the controls at the top left, and click between the PCA options, I seem to have a bug whereby clicking between 'Top 4-6' and 'Top 7-9' doesn't update the brain colormap. It does update the wordclouds, and clicking between 'Top 1-3' and either of the others does changes both the colormap and the wordcloud.

**Comment by PaulScotti** [comment]
Thanks for spotting this -- the wrong png was saved for "Top 7-9", it's now fixed.
