### ISSUE TITLE
Suggestion: Toggle PCA Wordcloud Viz On/Off

### ISSUE THREAD

**Issue by TomDonoghue** [PaulScotti/educortex#11]
Could there be a toggle to turn the PCA wordcloud on & off, just like how you can toggle the controls and associated papers displays on or off?

The reason is, when I turn on the ROI mapping on, and zoom into the brain to explore, the PCA wordcloud is in the way and overlaps on top of the brain in a sort of annoying manner.

**Comment by PaulScotti** [comment]
Added a button to the bottom right that allows turning the wordcloud on and off

**Comment by TomDonoghue** [comment]
Hey @PaulScotti - thanks for implementing this, just a note that I don't seem to see a way to turn the wordcloud back on..? When I click the wordcloud off, the button disappears, so it can't be clicked again. Can the button be set to stay there, just like the "Associated Studies" and "Open Controls" ones do?

**Comment by PaulScotti** [comment]
Ah thanks, yes I added an enable button. The PCA/wordcloud can also be reenabled by clicking the "Top x-y" button under the camera viewer.
