### ISSUE TITLE
add scores for associated terms

### ISSUE THREAD

**Issue by alexhuth** [PaulScotti/educortex#2]
It would be great to either (1) display the scores for the associated terms along with the terms, or (2) only display terms with high scores. For some voxels it seems like only a 1 or 2 terms have high scores, so showing the top 12 without any scores is a bit deceptive.

**Comment by PaulScotti** [comment]
In parentheses, added Neurosynth's z-scores to the associated terms (in descending order). Also made it so that if z-score was <= 0, then the term does not display.
