### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by TomDonoghue** [PaulScotti/educortex#6]
For the install instructions, they are (I think) currently a copy of some old instructions for installing `pycortex` (also, there is a typo in the line `python setup.py developpip install`). The instructions say to then proceed to use `runMappingViz.ipynb`, but this notebook has a series of extra dependencies over and above `pycortex` (including, for example `neurosynth` and `sklearn` - so without saying anything about these, the instructions are not sufficient to be able to run this project locally. 

My recommendation would be to:
- add a `requirements.txt` file, listing all dependencies, including `pycortex`, and what is needed to run the notebook. Install instructions can then say to install the dependencies listed in `requirements.txt`
- for pycortex itself (a more complex install), either just direct to the install instructions on their page, or at least update to the current instructions in their README, which allow for installing a stable version through from pypi.

There could also be other strategies to updating this - but I don't think the current instructions are ideal. 

Note: this issue filed as part of doing a review for JOSE (openjournals/jose-reviews#75)

**Comment by PaulScotti** [comment]
Added requirements.txt, changed our readme file to better convey install instructions, and edited the runMappingViz file to improve readability.

**Comment by TomDonoghue** [comment]
Hey @PaulScotti, I think the requiremnts file is good, but does it need to be so specific, in terms of exact version requirements? This looks like it comes from an environment description, but presumably any new versions of at least most of these requirements are fine, and it means it wouldn't make local setups have to change to these specific versions if they have newer version. 

Also, the readme could also note that you need to install requirements, so maybe step 2 could note something like:
``` 
# move into the cloned repository
cd educortex
# install the list of required dependencies
pip install -r requirements.txt
```

**Comment by PaulScotti** [comment]
Thanks, made the suggested changes. Sorry, the reason I was so specific is that I'm not very familiar with typical requirements.txt files, I thought it was supposed to be the exact version numbers in case later updates to a package lead to errors in the code. Thanks for the suggestions.

**Comment by TomDonoghue** [comment]
I think of a `requirements.txt` as a minimal requirements - so just module names, and any minimum versions, if there are any. But this is then more general, easier, than an environment file, which is what I think you had before basically, which a specific environment, with everything specified, which is sorta like an 'existence proof' of an environment that works. For install, I think one generally wants the general version, unless there is some reason one wants to mandate an exact overall environment (This is just my sense - not necessarily strict guidelines). 

Anyways - thanks for updating!
